DOCTOR_SEED = [
    {"id": 1, "name": "Dr. Aanya Rao", "specialty": "Cardiology", "department": "Heart Care", "disease_focus": ["Hypertension", "Heart attack", "Arrhythmia", "Heart failure"], "experience": 14, "rating": 4.9, "availability": "Mon, Wed, Fri", "initials": "AR"},
    {"id": 2, "name": "Dr. Karan Mehta", "specialty": "Neurology", "department": "Brain & Nerves", "disease_focus": ["Migraine", "Epilepsy", "Stroke", "Parkinson disease"], "experience": 11, "rating": 4.8, "availability": "Tue, Thu, Sat", "initials": "KM"},
    {"id": 3, "name": "Dr. Meera Shah", "specialty": "Orthopedics", "department": "Bone & Joint", "disease_focus": ["Arthritis", "Fracture", "Back pain", "Sports injury"], "experience": 16, "rating": 4.9, "availability": "Mon to Fri", "initials": "MS"},
    {"id": 4, "name": "Dr. Rohan Iyer", "specialty": "Pediatrics", "department": "Child Health", "disease_focus": ["Child fever", "Asthma in children", "Vaccination", "Growth concerns"], "experience": 9, "rating": 4.7, "availability": "Daily", "initials": "RI"},
    {"id": 5, "name": "Dr. Nisha Verma", "specialty": "Dermatology", "department": "Skin & Hair", "disease_focus": ["Acne", "Eczema", "Psoriasis", "Hair fall"], "experience": 12, "rating": 4.8, "availability": "Wed to Sun", "initials": "NV"},
    {"id": 6, "name": "Dr. Aditya Menon", "specialty": "General Medicine", "department": "Primary Care", "disease_focus": ["Fever", "Infection", "Diabetes", "Thyroid disease"], "experience": 18, "rating": 4.9, "availability": "24/7 Emergency", "initials": "AM"},
    {"id": 7, "name": "Dr. Sara Khan", "specialty": "Pulmonology", "department": "Lung Care", "disease_focus": ["Asthma", "COPD", "Pneumonia", "Tuberculosis"], "experience": 13, "rating": 4.8, "availability": "Mon, Tue, Thu", "initials": "SK"},
    {"id": 8, "name": "Dr. Vivek Sinha", "specialty": "Gastroenterology", "department": "Digestive Health", "disease_focus": ["Acidity", "IBS", "Liver disease", "Ulcer"], "experience": 15, "rating": 4.9, "availability": "Tue to Sat", "initials": "VS"},
    {"id": 9, "name": "Dr. Elena Morris", "specialty": "Endocrinology", "department": "Hormone Care", "disease_focus": ["Diabetes", "Thyroid disease", "PCOS", "Obesity"], "experience": 10, "rating": 4.7, "availability": "Mon, Wed, Sat", "initials": "EM"},
    {"id": 10, "name": "Dr. Harsh Patel", "specialty": "Nephrology", "department": "Kidney Care", "disease_focus": ["Kidney stones", "Chronic kidney disease", "UTI complications", "Dialysis care"], "experience": 17, "rating": 4.8, "availability": "Tue, Thu, Fri", "initials": "HP"},
    {"id": 11, "name": "Dr. Leena Kapoor", "specialty": "Urology", "department": "Urinary Health", "disease_focus": ["UTI", "Prostate disease", "Kidney stones", "Incontinence"], "experience": 12, "rating": 4.7, "availability": "Mon to Thu", "initials": "LK"},
    {"id": 12, "name": "Dr. Priyanka Bose", "specialty": "Gynecology", "department": "Women's Health", "disease_focus": ["Pregnancy care", "PCOS", "Menstrual disorders", "Menopause"], "experience": 14, "rating": 4.9, "availability": "Daily", "initials": "PB"},
    {"id": 13, "name": "Dr. Omar Malik", "specialty": "Oncology", "department": "Cancer Care", "disease_focus": ["Breast cancer", "Lung cancer", "Colon cancer", "Chemotherapy care"], "experience": 19, "rating": 4.9, "availability": "Mon, Wed, Fri", "initials": "OM"},
    {"id": 14, "name": "Dr. Kavya Reddy", "specialty": "ENT", "department": "Ear Nose Throat", "disease_focus": ["Sinusitis", "Ear infection", "Tonsillitis", "Hearing loss"], "experience": 10, "rating": 4.7, "availability": "Tue to Sat", "initials": "KR"},
    {"id": 15, "name": "Dr. Ethan Clarke", "specialty": "Ophthalmology", "department": "Eye Care", "disease_focus": ["Cataract", "Glaucoma", "Dry eye", "Vision problems"], "experience": 16, "rating": 4.8, "availability": "Mon to Fri", "initials": "EC"},
    {"id": 16, "name": "Dr. Farah Siddiqui", "specialty": "Psychiatry", "department": "Mental Health", "disease_focus": ["Anxiety", "Depression", "Insomnia", "Bipolar disorder"], "experience": 13, "rating": 4.8, "availability": "Wed to Sun", "initials": "FS"},
    {"id": 17, "name": "Dr. Arjun Nair", "specialty": "Rheumatology", "department": "Autoimmune Care", "disease_focus": ["Rheumatoid arthritis", "Lupus", "Gout", "Joint swelling"], "experience": 12, "rating": 4.7, "availability": "Mon, Thu, Sat", "initials": "AN"},
    {"id": 18, "name": "Dr. Maria Gomez", "specialty": "Infectious Disease", "department": "Infection Care", "disease_focus": ["Dengue", "Malaria", "COVID complications", "Sepsis follow-up"], "experience": 15, "rating": 4.8, "availability": "Tue, Fri, Sun", "initials": "MG"},
]

MEDICINE_SEED = [
    {"id": 101, "name": "Paracetamol 500mg", "category": "Pain Relief", "price": 4.99, "icon": "bi-capsule"},
    {"id": 102, "name": "Ibuprofen 200mg", "category": "Pain Relief", "price": 5.75, "icon": "bi-capsule"},
    {"id": 103, "name": "Aspirin 75mg", "category": "Heart Care", "price": 6.20, "icon": "bi-heart-pulse"},
    {"id": 104, "name": "Cetirizine 10mg", "category": "Allergy", "price": 3.80, "icon": "bi-wind"},
    {"id": 105, "name": "Loratadine 10mg", "category": "Allergy", "price": 4.25, "icon": "bi-wind"},
    {"id": 106, "name": "Cough Relief Syrup", "category": "Cold & Flu", "price": 6.40, "icon": "bi-droplet"},
    {"id": 107, "name": "Saline Nasal Spray", "category": "Cold & Flu", "price": 7.20, "icon": "bi-wind"},
    {"id": 108, "name": "Vitamin C Chewables", "category": "Vitamins", "price": 7.50, "icon": "bi-sun"},
    {"id": 109, "name": "Vitamin D3 Tablets", "category": "Vitamins", "price": 8.75, "icon": "bi-sun"},
    {"id": 110, "name": "Multivitamin Capsules", "category": "Vitamins", "price": 10.25, "icon": "bi-prescription2"},
    {"id": 111, "name": "Iron Folic Acid Tablets", "category": "Vitamins", "price": 6.90, "icon": "bi-prescription2"},
    {"id": 112, "name": "Calcium Tablets", "category": "Bone Health", "price": 8.10, "icon": "bi-prescription2"},
    {"id": 113, "name": "Antacid Chewables", "category": "Digestive Care", "price": 5.30, "icon": "bi-shield-plus"},
    {"id": 114, "name": "ORS Sachets", "category": "Digestive Care", "price": 2.50, "icon": "bi-droplet-half"},
    {"id": 115, "name": "Probiotic Capsules", "category": "Digestive Care", "price": 12.40, "icon": "bi-capsule"},
    {"id": 116, "name": "Omeprazole 20mg", "category": "Digestive Care", "price": 7.80, "icon": "bi-capsule"},
    {"id": 117, "name": "Digital Thermometer", "category": "Devices", "price": 12.50, "icon": "bi-thermometer-half"},
    {"id": 118, "name": "Pulse Oximeter", "category": "Devices", "price": 24.99, "icon": "bi-activity"},
    {"id": 119, "name": "Blood Pressure Monitor", "category": "Devices", "price": 42.00, "icon": "bi-heart-pulse"},
    {"id": 120, "name": "Glucometer Kit", "category": "Diabetes Care", "price": 35.00, "icon": "bi-droplet"},
    {"id": 121, "name": "Glucose Test Strips", "category": "Diabetes Care", "price": 18.60, "icon": "bi-droplet"},
    {"id": 122, "name": "Antiseptic Liquid", "category": "First Aid", "price": 5.95, "icon": "bi-bandaid"},
    {"id": 123, "name": "First Aid Kit", "category": "First Aid", "price": 18.00, "icon": "bi-bandaid"},
    {"id": 124, "name": "Sterile Gauze Pads", "category": "First Aid", "price": 4.20, "icon": "bi-bandaid"},
    {"id": 125, "name": "Adhesive Bandages", "category": "First Aid", "price": 3.60, "icon": "bi-bandaid"},
    {"id": 126, "name": "Antifungal Cream", "category": "Skin Care", "price": 7.45, "icon": "bi-brightness-high"},
    {"id": 127, "name": "Hydrocortisone Cream", "category": "Skin Care", "price": 6.35, "icon": "bi-brightness-high"},
    {"id": 128, "name": "Moisturizing Lotion", "category": "Skin Care", "price": 9.25, "icon": "bi-droplet"},
    {"id": 129, "name": "Sunscreen SPF 50", "category": "Skin Care", "price": 14.50, "icon": "bi-sun"},
    {"id": 130, "name": "Eye Lubricant Drops", "category": "Eye Care", "price": 8.90, "icon": "bi-eye"},
    {"id": 131, "name": "Oral Rehydration Liquid", "category": "Digestive Care", "price": 4.80, "icon": "bi-droplet-half"},
    {"id": 132, "name": "Zinc Tablets", "category": "Vitamins", "price": 5.60, "icon": "bi-prescription2"},
    {"id": 133, "name": "Electrolyte Powder", "category": "Wellness", "price": 9.10, "icon": "bi-lightning-charge"},
    {"id": 134, "name": "Sleep Support Melatonin", "category": "Wellness", "price": 11.20, "icon": "bi-moon"},
    {"id": 135, "name": "Hand Sanitizer", "category": "Hygiene", "price": 3.25, "icon": "bi-droplet"},
    {"id": 136, "name": "Disposable Face Masks", "category": "Hygiene", "price": 6.75, "icon": "bi-shield-check"},
]
